### ISSUE TITLE
Using slots in Layouts | Next.js

### ISSUE THREAD

**Issue by romancitodev** [Flammae/react-slots#5]
Hi, I saw this solution for slots and I loved the implementation, but for some reason the slots are not working for me.

Let me explain.
I have a layout for my page:

```tsx
import { Slot, SlotChildren, useSlot } from '@beqa/react-slots';

type HTMLButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement>;
type NewType = Omit<HTMLButtonProps, 'children'>;

type Props = NewType & {
	children: SlotChildren<Slot<'header'> | Slot>;
};

export default async function Layout({ children }: Props) {
	const session = await auth();

	const { slot, hasSlot } = useSlot(children);

	console.log(hasSlot);

	if (!session || !session.user) return;

	return (
		<div className='flex flex-col w-full h-full p-6 bg-zinc-100 gap-7'>
			<div className='flex gap-10 h-min'>
				<div className='w-full h-[90px] flex bg-white rounded-3xl shadow'>
					<slot.header>
						<header className='flex w-full items-center gap-5 justify-center'>
							<Capybara height='50' width='42.1' />
							<span className='font-bold text-2xl text-violet-600'>Capyshort</span>
						</header>
					</slot.header>
				</div>
				<SidebarWrapper session={session}>
					<Sidebar />
				</SidebarWrapper>
			</div>
			<div className='flex w-full h-0.5 items-center justify-center'>
				<span className='bg-stone-900 w-full h-full' />
			</div>
			<div className='w-full h-min'>
				<slot.default />
			</div>
		</div>
	);
}
```

And inside my `page.tsx` I render a `DashboardHome` component.

```tsx
export async function DashboardHome() {
	const session = await auth();

	if (!session || !session.user) return;

	const links = await getCardsByUser(session.user.id);

	return (
		<div className='grid w-full h-full gap-6'>
			<StoreLinks links={links} />
			<Filters slot-name='header' />
			<div className='flex h-full w-full gap-10 justify-between'>
				<UrlCards />
				<div className='grid w-2/6 h-full gap-6'>
					<TotalCards />
					<TotalClicks />
				</div>
			</div>
		</div>
	);
}
```

But like I said before, the slot isn't replaced by my custom slot (`Filters`).

I don't know if this just my skill issue or this is a real one.

**Comment by Flammae** [comment]
Hi, thanks for your interest!

slots aren't deeply integrated into NextJs app router. In order for slots to work, you have to wrap your children inside a slotted component yourself. In your case it would look like this:

```tsx
function DashboardHome() {
  return (
    <div>
      <Layout>
         <StoreLinks />
         <Filters slot-name="filters" />
      </Layout>
    </div>
  )
}
```
Of course, you'll have to rename layout.tsx into something different to not conflict with NextJs app router.

Btw NextJs has its own concept of slots based on file system that might be more appropriate for this situation: https://nextjs.org/docs/app/building-your-application/routing/parallel-routes

**Comment by romancitodev** [comment]
I wrapped the `layout.tsx` component inside a new file `slot-layout.tsx` where I render the children:

```tsx
export function SlotProvider({ children, session }: Props) {
	const { slot, hasSlot } = useSlot(children);

	console.log(hasSlot);

	return (
		<div className='flex flex-col w-full h-full p-6 bg-zinc-100 gap-7'>
			<div className='flex gap-10 h-min'>
				<div className='w-full h-[90px] flex bg-white rounded-3xl shadow'>
					<slot.header>
						<header className='flex w-full items-center gap-5 justify-center'>
							<Capybara height='50' width='42.1' />
							<span className='font-bold text-2xl text-violet-600'>Capyshort</span>
						</header>
					</slot.header>
				</div>
				<SidebarWrapper session={session}>
					<Sidebar />
				</SidebarWrapper>
			</div>
			<div className='flex w-full h-0.5 items-center justify-center'>
				<span className='bg-stone-900 w-full h-full' />
			</div>
			<div className='w-full h-min'>
				<slot.default />
			</div>
		</div>
	);
}
``` But its the same behaviour. Do I have to render this 'slot-layout' in page.tsx instead of layout.tsx ?

**Comment by romancitodev** [comment]
Well, I wrapped all inside `page.tsx` instead of `layout.tsx` and is the same behaviour.

**Comment by Flammae** [comment]
It doesn't matter where you render slot-layout as long as you import and render yourself. I made this quick demo you can take a look: https://stackblitz.com/edit/stackblitz-starters-zhymws?description=The%20React%20framework%20for%20production&file=app%2Fslot-layout.tsx,next.config.js,app%2Fpage.tsx,app%2Fstore-links.tsx,app%2Ffilters.tsx&title=Next.js%20Starter

**Comment by romancitodev** [comment]
Really thanks! I'm gonna inspect this! Thanks in advance

**Comment by romancitodev** [comment]
Well, after a quick research, I was able to find out that in order to render the slots I want, the Slotted Component has to have a direct child slot.

Which makes me unable to render things in my Layout.tsx because it receives the children and no longer has the direct child the Slotted Component.
Here is a reference:

```tsx
// this works correctly:

return (
    <div className='grid w-full h-full gap-6'>
      <SlotLayout>
        <StoreLinks />
	<Filters slot-name='header' />
      </SlotLayout>
    </div>
);

// This works too:

return (
    <SlotLayout>
      <Filters slot-name="header" />
      <div className="grid w-full h-full gap-6">
        <StoreLinks />
      </div>
    </SlotLayout>
  );

```



```tsx
// this don't work :(
  return (
    <SlotLayout>
      <div className="grid w-full h-full gap-6">
        <Filters slot-name="header" />
        <StoreLinks />
      </div>
    </SlotLayout>
  );
```

**Comment by romancitodev** [comment]
Well, I think I found the main issue.

I think that when Next.js builds the page and visits the `layout.tsx` it grabs the `page.tsx` and passes it as `children` but re-exports it as a generic component, making it visually represent this way.
```ts
// layout.tsx
export default function Layout({ children }) {
  return <SlotLayout>{children}</SlotLayout>;
}

// page.tsx
export default function Page() {
  return <Comp slot-name='header' />
}
```

This is how you would represent it
````tsx
export default function Layout() {
  return <SlotLayout><Page><Comp slot-name=''/></Page></SlotLayout>;
}
```

**Comment by romancitodev** [comment]
seeing more documentation about your lib, I found that there are templates, maybe that will help me instead of having to wrap inside each page.tsx my `SlotLayout` component, maybe I can make a generic component in my layout.tsx and this if I can infer that I have the templates inside.

**Comment by Flammae** [comment]
Templates are just type-safe alternative to using slot-name attributes so it's probably not what you are looking for. What you described is pretty much how NextJs works under the hood. Unfortunately, there's no way to make layouts slotted components, because under the hood layouts receive <Page /> components as children and not slotted children (i.e. elements labeled with slot-name or template elements)

**Comment by romancitodev** [comment]
Ok, got it! Thank you very much for everything and for your patience to explain these things to me.

I would like that the issue is not deleted because there may be more people who had the same thing happen to him and I think that even if we find the explanation to the problem and a possible patch.

**Comment by Flammae** [comment]
It's no problem at all! I'm very glad you gave it a try. 

The only way I think this could work is if NextJs allowed exporting of elements directly from page.tsx

```tsx
// page.tsx

export default const page = ([
  <Filters slot-name="filters" />
  <StorLinks />
])

// instead of 
export default function Page () { ... }
```

To my knowledge this is not possible but maybe someday...
